const engine = {
  apiEndpoint: "https://localhost/api/appsearch/",
  searchPath: "search/",
  clickPath: "analytics/click",
  querySuggestionPath: "suggestions/",
  engineName: "dummy",
  endpointBase: "dummy",
  resultFields: [
    "country",
    "urltitle",
    "releasedate",
    "comingsoon",
    "isdiscontinued",
    "score",
    "price",
    "fullproduct",
    "distilleryurl",
    "volume",
    "atomstock",
    "stockincoming",
    "rrp",
    "hasactivelightningdeal",
    "vintage",
    "style",
    "bottlingyear",
    "region",
    "preorder",
    "previousprice",
    "distillery",
    "hasdram",
    "description",
    "bottler",
    "title",
    "stocklevel",
    "productimage",
    "isdiscounted",
    "productstatus",
    "discountflag",
    "hasfreeshipping",
    "userrating",
    "maxnumberpercustomer",
    "searchfield",
    "url",
    "hasfreeshippingworldwide",
    "targettemplate",
    "reviewcount",
    "abv",
    "ranking",
    "isvatableproduct",
    "age",
    "id",
    "freestock"
  ],
  sortFields: ["userrating", "price", "title", "releasedate"],
  facets: [
    "hasfreeshipping",
    "price",
    "userrating",
    "age",
    "vintage",
    "bottlingyear",
    "abv",
    "stocklevel",
    "targettemplate",
    "style",
    "countryid",
    "targettemplate",
    "volume",
    "region",
    "distillery",
    "volume",
    "isdiscounted"
  ],
  titleField: "title",
  urlField: "url",
  thumbnailField: "productimage"
};

export default engine;
